### ISSUE TITLE
jcardSIM in CLI mode with BixVReader: fileNotFound error

### ISSUE THREAD

**Issue by AndreaPasconcino** [licel/jcardsim#114]
Please,
 could anyone help me to solve the issue I am detecting calling
java -cp %classpath% com.licel.jcardsim.remote.BixVReaderCard jcardsim.cfg ?

The rror message is  
\\.\pipe\SCardSimulatorDriver0 (The system cannot find the file specified) ,
        at java.io.RandomAccessFile.open0(Native Method)
        at java.io.RandomAccessFile.open(Unknown Source)
        at java.io.RandomAccessFile.<init>(Unknown Source)
        at java.io.RandomAccessFile.<init>(Unknown Source)
        at com.licel.jcardsim.remote.BixVReaderIPCProtocol.connect(BixVReaderIPC
Protocol.java:41)
        at com.licel.jcardsim.remote.BixVReaderCard.<init>(BixVReaderCard.java:3
8)
        at com.licel.jcardsim.remote.BixVReaderCard.main(BixVReaderCard.java:75)

I am newcomer with jcardsim

Thank you in advance

best regards
Andrea

**Comment by AndreaPasconcino** [comment]
solved
