### ISSUE TITLE
SystemException on installing applet

### ISSUE THREAD

**Issue by behnejad** [licel/jcardsim#125]
Hi.
i am getting this SystemException when my applet class is going to install.
`Exception in thread "main" javacard.framework.SystemException
	at javacard.framework.SystemException.throwIt(Unknown Source)
	at com.licel.jcardsim.base.Simulator.createApplet(Simulator.java:179)
	at com.licel.jcardsim.base.Simulator.installApplet(Simulator.java:219)
	at com.licel.jcardsim.base.Simulator.installApplet(Simulator.java:195)`

my applet works on real java card (both version 2.2 and 3) but it is failed to install on simulation.
does it come from my applet or something else?

**Comment by stone-ktsujino** [comment]
I am having same issue.

**Comment by liyanhrxy** [comment]
> Hi.
> i am getting this SystemException when my applet class is going to install.
> `Exception in thread "main" javacard.framework.SystemException at javacard.framework.SystemException.throwIt(Unknown Source) at com.licel.jcardsim.base.Simulator.createApplet(Simulator.java:179) at com.licel.jcardsim.base.Simulator.installApplet(Simulator.java:219) at com.licel.jcardsim.base.Simulator.installApplet(Simulator.java:195)`
> 
> my applet works on real java card (both version 2.2 and 3) but it failed to install on simulation.
> does it come from my applet or something else?

have you solved ??

**Comment by gahcep** [comment]
Hi @liyanhrxy 
Successfully passed the `installApplet` function call while previously got stuck on the same System Exception.
In my case the applet itself causes this by invoking a crypto function with non-existing on simulator's JC implementation crypto parameters. And @behnejad probably had the same issue. Usually smartcards have their own HW blocks and proprietary JC libs implementations.
Anyway, thanks @licel for his work.
