### ISSUE TITLE
CAP files simulation & Security domain

### ISSUE THREAD

**Issue by Aiosa** [licel/jcardsim#152]
Hello, 

is it possible to simulate CAP file applets through cli/virtual reader?

I tried following:

```
com.licel.jcardsim.card.applet.0.Class=JCMemory.JCMemoryApplet
; -- and
com.licel.jcardsim.card.applet.0.Class=JCMemory.javacard.Applet
; -- and
com.licel.jcardsim.card.applet.0.Class=javacard.Applet
```

while providing the .cap file in the classpath. Tried both cli

> Unable to execute demo.apdu due to: null

and BixVReader

> Exception in thread "main" javacard.framework.SystemException
>         at javacard.framework.SystemException.throwIt(SystemException.java:87)
>         at com.licel.jcardsim.base.Simulator.loadApplet(Simulator.java:113)
>         at com.licel.jcardsim.base.Simulator.<init>(Simulator.java:80)
>         at com.licel.jcardsim.remote.BixVReaderCard.<init>(BixVReaderCard.java:35)
>         at com.licel.jcardsim.remote.BixVReaderCard.main(BixVReaderCard.java:73)

in all the cases. The helloworld demo works. 

Also, I tried to use the simulated card with normal tools (gppro) and got 0x6999 on selecting the SD applet -- does the card have "security domain" - emulate the functionality along with SD - AID (A00..0030000... etc.) ?

Thanks a lot!

**Comment by Aiosa** [comment]
The latter seems to be part of the GlobalPlatform commercial module

**Comment by dogtopus** [comment]
IIRC jcardsim "links" with the javacard applet source code instead of being a full javacard VM. So no execution of CAP files.
