### ISSUE TITLE
Issue while using it for PIV applet

### ISSUE THREAD

**Issue by snlgaba** [licel/jcardsim#175]
Hi,

First of all, thanks for the great work.

I am trying to use this simulator to run PIV Applet: https://github.com/arekinath/PivApplet

It currently fails when trying to perform signature.

Exception:
javacard.security.CryptoException
at javacard.security.CryptoException.throwIt(Unknown Source)
at com.licel.jcardsim.crypto.AsymmetricCipherImpl.update(AsymmetricCipherImpl.java:115)
at com.licel.jcardsim.crypto.AsymmetricCipherImpl.doFinal(AsymmetricCipherImpl.java:92)

However, if i use jcardSim fork with following commit: https://github.com/arekinath/jcardsim/commit/5574374559598f79be4483081784ddd1f660bcfc

it works fine.

The main change in the commit is the buffer size in AsymmetricCipherImpl.

Can you please help me understand why there is a discrepancy for PIV card? Also, is there any way that commit can be merged into the mainline?

**Comment by koh-osug** [comment]
I have merged in several pull requests in [my version](https://github.com/koh-osug/jcardsim/tree/master) which might address this. See https://github.com/koh-osug/jcardsim/blob/master/src/main/java/com/licel/jcardsim/crypto/AsymmetricCipherImpl.java#L77
The latest released jars are addressing this.
