### ISSUE TITLE
Exception when loading applet

### ISSUE THREAD

**Issue by xhanulik** [licel/jcardsim#205]
Hello, I'm trying to use OpenFIPS201 applet with jcardsim. However, it seems that I need help to get through. I have CAP file and jcardsim.cfg, but starting the applet with command
```
java -noverify -cp OpenFIPS201/build/bin:jcardsim/target/jcardsim-3.0.5-SNAPSHOT.jar com.licel.jcardsim.remote.VSmartCard jcardsim.cfg
```
ends with exception
```
Exception in thread "main" javacard.framework.SystemException
	at javacard.framework.SystemException.throwIt(Unknown Source)
	at com.licel.jcardsim.base.Simulator.loadApplet(Simulator.java:146)
	at com.licel.jcardsim.base.Simulator.<init>(Simulator.java:114)
	at com.licel.jcardsim.base.Simulator.<init>(Simulator.java:65)
	at com.licel.jcardsim.remote.VSmartCard.startThread(VSmartCard.java:87)
	at com.licel.jcardsim.remote.VSmartCard.<init>(VSmartCard.java:43)
	at com.licel.jcardsim.remote.VSmartCard.main(VSmartCard.java:83)
```
Do you have any idea what might be causing the problem?

**Comment by makinako** [comment]
Hi, as I understood the free version of jCardSim doesn't support GlobalPlatform. Since OpenFIPS201 makes use of this for SCP03 and Global CVM support, I'm not sure the cap will install as the dependent packages wouldn't be there. It's been a while since I looked so I may be wrong about this.

**Comment by licel** [comment]
This functionality (SCP03, Global CVM) is supported in our commercial jCardSim GP product. Please use the contact form https://licelus.com/get-a-quote to obtain more details.

**Comment by no-usernames-left** [comment]
@licel Would you be willing to extend a license to the developers of OpenSC to contribute to the ecosystem? This would allow them to improve their CI.

https://github.com/OpenSC/OpenSC/discussions/3165#discussioncomment-9617586
